### ISSUE TITLE
RFC: aws_security_group resource planning

### ISSUE THREAD

**Issue by aaronlippold** [chef/inspec-aws#129]
# Overview  
The `aws_security_group` and `aws_security_groups` resources will interrogate the S3 bucket api and buckets in a VPC. Below is the start at articulating the general questions that we should like the resource to start to be able to answer.

## Questions / Capabilities of the Resource ( need feedback ) 

- [ ] the VPC is assigned to or not assigned to a security group and or part of a security group.
- [ ] list all the security groups that are part of this VPC or IAM_role
- [ ] ... ( please add )

## Code / InSpec Examples ( rough, poke at me - not perfect yet )
```
describe aws_security_groups.where(vpc: 'vpc_id') do 
  its('security_groups') { should be_in [a,b,c,d] }
end
```

```
describe aws_security_groups.where(vpc: 'vpc_id') do 
  its('security_groups') { should_not contain /bad_group/ }
end
```

```
# still working the idea behind this one
describe aws_security_group.id('sg_id') do 
  its('vpcs') { should be_in [a,b,c] }
  its(...) { ... }
  it { should ... }
end
```

**Comment by chris-redekop** [comment]
> The aws_security_group and aws_security_groups resources will interrogate the S3 bucket api and buckets in a VPC.

I don't understand how security groups overlap with S3--do they, or is this a typo?

Our current resource-naming convention adheres to `aws_<service>_<resource>`.  [Security groups fall under the EC2 service](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/SecurityGroup.html), so I recommend that the InSpec resource be named `aws_ec2_security_group` or `aws_ec2_sg`or similar.

For the first two examples, the `describe` line already specifies a list of security groups, so I wonder if it should just be

```
  it { should be_in [a, b, c, d] }
```

and

```
  it { should_not contain /bad_group/ }
```

Also, security groups are made available through a VPC, but are made *active* by attaching them to an instance.  I wonder, then, if instance attachment should be a first use case, instead of VPC inclusion?

**Comment by clintoncwolfe** [comment]
Hi @aaronlippold,
  So, reading over what you propose, a couple of things poke out for me.

- I think you might have the containment relationship between VPCs and security groups inverted.  A security group is in exactly one VPC, and a VPC can have many security groups.
- Security groups (which are similar to firewall rules, and are attached to instances) are different than IAM groups (which are lists of IAM users).  Both can be referenced from IAM policies.
- An s3 bucket can have several different types of policies attached, including custom ones that might reference security groups or IAM groups or vpc_ids; determining that would require either using the policy query API, or locally interpreting the policy. 

So, based on that, I might say this: 
```
  # Ensure a named VPC has a named security group
  aws_vpc('web-team') do
    its('security_group_names') { should include('backend-to-db') }
  end  
```

I'm not sure how to address s3 policy issues yet, but the "how do we interpret policies" problem is being worked elsewhere.

Otherwise, most of my use cases for security groups are related to their firewall rules.  Are they open to the world at all?  How many instances are assigned this SG?

Overall though - as I mentioned on [#91](https://github.com/chef/inspec-aws/issues/91#issuecomment-349098540) - we'd want to have a minimal resource first, that can just do search, before we started adding in specific use cases.

**Comment by clintoncwolfe** [comment]
#135 and #136 provide basic singular and plural security group resources.

**Comment by clintoncwolfe** [comment]
This thread has been great for clarifying  what we're looking for in a security group - thanks everyone!  Now that we have the skeleton `aws_ec2_security_group` and `aws_ec2_security_groups`, let's open individual issues for new functionality we'd like added.  That way we can explore the use cases individually.
