### ISSUE TITLE
RFC: Should add the full test suite to pull requests and have a 'destroy=always' at the end for testing PRs

### ISSUE THREAD

**Issue by aaronlippold** [chef/inspec-aws#144]
This would make it very simple to see and approve changes if we keep things small. 

Is there a cost for running our tests if we ensure that we are always destroying the build and randomizing the 'testbed' name?

**Comment by clintoncwolfe** [comment]
Hi @aaronlippold , 
  Thanks for your question!  I'm afraid I don't quite follow what you're proposing, but I'll explain how we at Chef think about the inspec-aws integration tests.

Whenever I examine a pull request, I check the integration tests for code changes, then run the full suite (e.g., `bundle exec rake test:aws`).  Chef currently does not run the integration tests under automated CI when a PR is submitted, due to risk of abuse.  

When an integration test run is performed, it creates all resources specified by the Terraform code in AWS, runs the tests, then destroys the entire infrastructure using `terraform destroy --force`, which is not resource-specific - it destroys everything that TF knows about.  There is no need to set `destroy=always` on specific TF resources (which is unusual anyway), because none are intended to survive even one test cycle.

As for cost, the setup is intended to be very cheap (only running a pair of `t2`s so far, and that only for a few minutes).  Outside of the test fixtures, you are free to setup cost control measures using tools such as AWS Budget.

Does that clear anything up?

**Comment by aaronlippold** [comment]
I think I didn't say that well. What I was wondering was could we setup a travis job that actually runs the integration test suite when we push a PR like we do with inspec core. I wasn't sure if that would be possible given the env_var setup we have to do but if the test run was a low cost event, if we could set via travis the env_vars for a set of AWS accounts that could run the jobs as we push PRs.

**Comment by adamleff** [comment]
@aaronlippold we will not be pursuing that option due to the abuse concern @clintoncwolfe has already called out. Someone could open 100+ PRs and Chef would be left holding the bill for any resources that are spun up as a result of the travis job.
