### ISSUE TITLE
[SPIKE] aws_iam_user and aws_iam_access_key for Recommendation 1.3

### ISSUE THREAD

**Issue by chris-redekop** [chef/inspec-aws#38]
We have user and access-key resources. What else do we need before we can implement a test for Recommendation 1.3?

**Comment by mtjandra** [comment]
I believe we are only missing the portion to check when the user last used their console password is. See relevant resources [1](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_finding-unused.html), [2](http://docs.aws.amazon.com/IAM/latest/APIReference/API_GenerateCredentialReport.html) and [3](http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Client.html#generate_credential_report-instance_method). I think once https://github.com/chef/inspec-aws/pull/44/files is merged we should be able to verify the last usage times of access keys nicely.

```
aws_iam_user(some_user).access_keys.each { |access_key|
  describe access_key do
    its('last_used_date') { should be > Time.now - 90 * 86400 }
  end
}
```

**Proposal:** Create issue to address last used console password date for resource `aws_iam_user.rb`

**Comment by chris-redekop** [comment]
Thanks for taking a look at this, @mtjandra .

On, *"check if the console password is enabled"*, I think we already have this with **has_console_password?**.  (If I understand AWS correctly, then there is no difference between disabling a console password and removing it; AWS won't keep track of disabled passwords, it just deletes them.)

On, *"check when the user last used their console password"*, I don't think the SDK gives us a way to do this.  Looking at [LoginProfile](http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Types/LoginProfile.html), which is returned by both [get_login_profile](http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Client.html#get_login_profile-instance_method) and [login_profile](http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/User.html#login_profile-instance_method), I don't see the last-used date that we are looking for.

I think we should avoid using the credential report.  AWS only commits to updating the report every four hours; so while It's good for human-scale checks it will give us stale results (with false positives and negatives).

I currently don't see a good way to get the last-used date of a user's console password.  Without one, I think we can implement the access-key portion of Recommendation 1.3, but **not** the login-profile portion.  I am open to any ideas or findings!

**Comment by mtjandra** [comment]
Thanks for the feedback @chris-redekop.

> On, *"check if the console password is enabled"*, I think we already have this with **has_console_password?**. 

Yes you are right, I confirmed by testing it on my own user. From reading the documentation of the ruby SDK alone, it wasn't clear to me that the `login_profile` cannot be accessed when the console password is disabled.


> On, "check when the user last used their console password", I don't think the SDK gives us a way to do this. 

I could not find a way to do this either, other than using the [credential report](http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Client.html#generate_credential_report-instance_method). If the data being real time is a requirement, then it does not seem possible to do. Although [get_credential_report](http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Client.html#get_credential_report-instance_method) does provide a [timestamp](http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Types/GetCredentialReportResponse.html#generated_time-instance_method) of when the report was generated. So we could leave it up to the auditor/test implementer to place their own conditions on the freshness of the report, marking the result as void or valid accordingly. This doesn't sound too crazy since the `AWS_CIS_Foundations_Benchmark` we are following does recommend downloading the credentials report manually, and provided a CLI example.

Sounds like a consensus needs to be made by the project maintainers, on if the benefits of providing information that can be hours stale (along with the timestamp), outweighs the risk of users writing tests with the false belief the data is fresh.

Given we document our project, I would like to allow users to access this information. But considering the credential report is dependent on first waiting on the report to be generated, and we would be parsing a raw csv formatted string, I also sway on the side of not implementing the login-profile portion. If you are not using AWS programmatically, perhaps auditing this case in a non-programmatic way is also acceptable.

If nobody feels strongly about checking the login-profile section, I think this issue can be closed, with no follow up actions needed. (Unless maybe verifying the access-key portion actually works).

**Comment by chris-redekop** [comment]
Looking to close this one as "no fix" at standup this week.  @chris-rock , @mtjandra , @vix633 , @AlexBedley , @Stiffni , @aduric , @Rugbyte , let us know before then if you have any concerns with closing.

**Comment by chris-redekop** [comment]
Closed as "no fix".
