### ISSUE TITLE
Determine Integration Tests for Root User Access Key Count

### ISSUE THREAD

**Issue by mtjandra** [chef/inspec-aws#58]
See https://github.com/chef/inspec-aws/pull/49 . It would be good to have a deterministic integration test to cover the following case:

```
describe aws_iam_root_user do
  its('access_key_count') { should eq 0 }
end
```

Once the test is complete the account should be reverted to its previous state.

**Comment by chris-redekop** [comment]
I see three things that we need to make this work:
1. A mechanism to set/revert the root user's access keys.  I currently don't see a way to do this with Terraform, so we might need to setup the integration tests.
2. A way to keep the test setup/teardown isolated and from disrupting other users.  I think the best solution here would be to create a dedicated AWS account for CI via Travis.
3. A test flag/grouping to exclude such "I am changing the target account for everybody" tests, so that we can run the (other) integration tests in a shared account.

**Comment by clintoncwolfe** [comment]
This is in place in #128.
